version: '3.8'

services:
  # Frontend Nuxt.js
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-frontend
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
      - API_URL=http://backend:3001
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - portfolio-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Backend Express.js
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: portfolio-backend
    environment:
      - PORT=3001
      - NODE_ENV=production
    env_file:
      - ./backend/.env.production
    networks:
      - portfolio-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Proxy Nginx avec Let's Encrypt
  nginx:
    image: nginx:alpine
    container_name: portfolio-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - certbot_certs:/etc/letsencrypt:ro
      - certbot_www:/var/www/certbot:ro
    depends_on:
      - frontend
      - backend
    networks:
      - portfolio-network
    restart: unless-stopped

  # Certbot pour Let's Encrypt
  certbot:
    image: certbot/certbot
    container_name: portfolio-certbot
    volumes:
      - certbot_certs:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email votre-email@gmail.com --agree-tos --no-eff-email -d votre-domaine.nc.me -d www.votre-domaine.nc.me
    depends_on:
      - nginx
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge

volumes:
  certbot_certs:
  certbot_www:
