version: "3.9"

services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    command:
      - "--api.dashboard=true"
      - "--api.insecure=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.letsresolver.acme.email=amirotalbi94@gmail.com"
      - "--certificatesresolvers.letsresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsresolver.acme.httpchallenge.entrypoint=web"
      - "--log.level=DEBUG"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.amirtalbi.me`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls.certresolver=letsresolver"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$hG9dpSzk$$d/czKXcpEf8w.KvZgTnps0"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt:Z"
    networks:
      - portfolio-network

  frontend:
    image: ghcr.io/amirtalbi/front-portfolio:1.0.0
    container_name: frontend
    platform: linux/amd64
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`amirtalbi.me`)"
      - "traefik.http.routers.frontend.entrypoints=web,websecure"
      - "traefik.http.routers.frontend.tls.certresolver=letsresolver"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
    expose:
      - "3000"
    networks:
      - portfolio-network

  mongo:
    image: mongo:4.4
    container_name: mongo
    platform: linux/amd64
    environment:
      MONGO_INITDB_ROOT_USERNAME: jefe_dz
      MONGO_INITDB_ROOT_PASSWORD: password91_secure!
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - portfolio-network

  go-vtc-api:
    image: ghcr.io/amirtalbi/vtc-portfolio:1.0.0
    container_name: go-vtc-api
    platform: linux/amd64
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.govtc.entrypoints=web,websecure"
      - "traefik.http.routers.govtc.tls.certresolver=letsresolver"
      - "traefik.http.services.govtc.loadbalancer.server.port=3000"
      - "traefik.http.routers.govtc.rule=Host(`go-vtc.amirtalbi.me`)"
    expose:
      - "3000"
    environment:
      - MONGODB_URI=mongodb://jefe_dz:password91_secure!@mongo:27017/auth-api?authSource=admin
      - NODE_ENV=production
    depends_on:
      - mongo
    networks:
      - portfolio-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "3000"]
      interval: 30s
      timeout: 5s
      retries: 3

  morpion-back:
    image: ghcr.io/amirtalbi/morpion-back-portfolio:1.0.0
    container_name: morpion-back
    platform: linux/amd64
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.morpion-back.rule=Host(`morpion-back.amirtalbi.me`)"
      - "traefik.http.routers.morpion-back.entrypoints=web,websecure"
      - "traefik.http.routers.morpion-back.tls.certresolver=letsresolver"
      - "traefik.http.services.morpion-back.loadbalancer.server.port=3001"
    expose:
      - "3001"
    networks:
      - portfolio-network

  morpion-front:
    image: ghcr.io/amirtalbi/morpion-front-portfolio:1.0.0
    container_name: morpion-front
    platform: linux/amd64
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.morpion-front.rule=Host(`morpion-front.amirtalbi.me`)"
      - "traefik.http.routers.morpion-front.entrypoints=web,websecure"
      - "traefik.http.routers.morpion-front.tls.certresolver=letsresolver"
      - "traefik.http.services.morpion-front.loadbalancer.server.port=3000"
    expose:
      - "3000"
    networks:
      - portfolio-network

  morpion:
    image: ghcr.io/amirtalbi/morpion-portfolio:1.0.0

networks:
  portfolio-network:
    driver: bridge
    name: portfolio-network

volumes:
  mongo_data:
