version: "3.9"

services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    command:
      - "--api.dashboard=true"
      - "--entrypoints.web.address=:80"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - "80:80"
      - "8080:8080" # dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.amirtalbi.me`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=web"

  frontend:
    image: ghcr.io/amirtalbi/front-portfolio:1.0.0
    container_name: frontend
    platform: linux/amd64
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`amirtalbi.me`)"
      - "traefik.http.routers.frontend.entrypoints=web"
    expose:
      - "3000"

  backend:
    image: ghcr.io/amirtalbi/back-portfolio:1.0.0
    container_name: backend
    platform: linux/amd64
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.amirtalbi.me`)"
      - "traefik.http.routers.backend.entrypoints=web"
    expose:
      - "3001"
