services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.letsresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.letsresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsresolver.acme.email=amirotalbi94@gmail.com"
      - "--certificatesresolvers.letsresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.amirtalbi.me`)"
      - "traefik.http.routers.dashboard.entrypoints=web"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$Phe9uh4t$$YUc2w9.EpcjA1yifs80qW0"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - portfolio-network

  frontend:
    image: ghcr.io/amirtalbi/front-portfolio:1.0.0
    container_name: frontend
    platform: linux/amd64
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`amirtalbi.me`)"
      - "traefik.http.routers.frontend.entrypoints=web,websecure"
      - "traefik.http.routers.frontend.tls.certresolver=letsresolver"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
    expose:
      - "3000"
    depends_on:
      - traefik
    networks:
      - portfolio-network

  mongo:
    image: mongo:4.4
    container_name: mongo
    platform: linux/amd64
    environment:
      MONGO_INITDB_ROOT_USERNAME: jefe_dz
      MONGO_INITDB_ROOT_PASSWORD: password91_secure!
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - portfolio-network

  go-vtc-api:
    image: ghcr.io/amirtalbi/vtc-portfolio:1.0.0
    container_name: go-vtc-api
    platform: linux/amd64
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.govtc.rule=Host(`go-vtc.amirtalbi.me`)"
      - "traefik.http.routers.govtc.entrypoints=websecure"
      - "traefik.http.routers.govtc.tls=true"
      - "traefik.http.routers.govtc.tls.certresolver=letsresolver"
      - "traefik.http.services.govtc.loadbalancer.server.port=3000"
    expose:
      - "3000"
    environment:
      - MONGODB_URI=mongodb://jefe_dz:password91_secure!@mongo:27017/auth-api?authSource=admin
      - NODE_ENV=production
    depends_on:
      - mongo
      - traefik
    networks:
      - portfolio-network
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: jefe_dz
      MONGO_INITDB_ROOT_PASSWORD: password91_secure!
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    depends_on:
      - frontend
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge

volumes:
  mongo_data:
