version: "3.9"

services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    command:
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.letsresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.letsresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsresolver.acme.email=ton@email.com"
      - "--certificatesresolvers.letsresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - portfolio-network

  frontend:
    image: ghcr.io/amirtalbi/front-portfolio:1.0.0
    container_name: frontend
    platform: linux/amd64
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`amirtalbi.me`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=letsresolver"
    expose:
      - "3000"
    networks:
      - portfolio-network

  backend:
    image: ghcr.io/amirtalbi/back-portfolio:1.0.0
    container_name: backend
    platform: linux/amd64
    environment:
      - EMAIL_SERVICE=gmail
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - OWNER_EMAIL=${OWNER_EMAIL}
      - FRONTEND_URL=https://amirtalbi.me
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.amirtalbi.me`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.tls.certresolver=letsresolver"
    expose:
      - "3001"
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge
