[build]
  publish = ".output/public"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Redirection automatique HTTP vers HTTPS
[[redirects]]
  from = "http://amirtalbi.me/*"
  to = "https://amirtalbi.me/:splat"
  status = 301
  force = true

# Redirection www vers non-www (optionnel)
[[redirects]]
  from = "https://www.amirtalbi.me/*"
  to = "https://amirtalbi.me/:splat"
  status = 301
  force = true

# SPA fallback pour les routes dynamiques
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de sécurité pour HTTPS
[[headers]]
  for = "/*"
  [headers.values]
    # Force HTTPS
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    
    # Protection contre le clickjacking
    X-Frame-Options = "DENY"
    
    # Protection XSS
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    
    # Référence policy
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Content Security Policy (ajustez selon vos besoins)
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https:; style-src 'self' 'unsafe-inline'; script-src 'self'; font-src 'self' data:;"
